FROM ubuntu:16.04
WORKDIR /workspace


RUN apt update

RUN apt install bc libelf-dev bison bc autotools-dev libncurses5-dev flex -y
RUN apt install vim cmake git gcc make build-essential libssl-dev e2fsprogs -y
RUN apt install bear -y
