FROM ubuntu:18.04
WORKDIR /workspace

RUN apt-get update

RUN apt-get install bc libelf-dev bison bc autotools-dev libncurses5-dev flex -y
RUN apt-get install vim cmake git gcc make build-essential libssl-dev -y
RUN apt-get install bear -y
