FROM ubuntu:14.04
WORKDIR /workspace


RUN sudo apt update

RUN sudo apt install bc libelf-dev bison bc autotools-dev libncurses5-dev flex -y
RUN sudo apt install vim cmake git gcc make build-essential libssl-dev e2fsprogs -y

