version: '3.7'
services:
  blog:
    # build: .
    image: jekyll/jekyll:latest
    ports:
      - 5000:4000/tcp
    volumes:
      - ./:/srv/jekyll
    environment:
      - JEKYLL_ENV=docker
    command: jekyll serve
