FROM ubuntu:14.04
WORKDIR /workspace


RUN apt update && apt upgrade -y
RUN apt install bc libelf-dev libc6-dev bison bc autotools-dev libncurses5-dev flex -y
RUN apt install vim cmake git gcc make build-essential libssl-dev -y